# Generated by Django 4.1.7 on 2023-03-28 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Бренд')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='brands/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Лінійка')),
                ('position', models.SmallIntegerField(blank=True)),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='lines/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Лінійка')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('articul', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('properties', models.TextField(blank=True, verbose_name='Характеристики')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brnd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
