# Generated by Django 4.1.7 on 2023-04-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_popular_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Лінія')),
                ('description', models.CharField(max_length=255, verbose_name='Опис')),
                ('image', models.ImageField(blank=True, upload_to='lines/%Y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.brand')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
